# Generated by Django 5.0.3 on 2024-03-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', null=True)),
                ('mob', models.BigIntegerField(db_column='mob', null=True)),
                ('email', models.TextField(db_column='email', null=True)),
                ('repass', models.TextField(db_column='password', null=True)),
            ],
        ),
    ]
