# Generated by Django 5.0.3 on 2024-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_course_remove_product_category_delete_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.TextField(db_column='title', null=True),
        ),
    ]
